# This file configures the "/show-diff" slash command
name = "show-diff"
description = "Shows the git diff for the latest DCI deployment of an application."

[[argument]]
name = "application_name"
description = "The AppHub application ID (e.g., dci-test-app)."
type = "string"
required = true

[[argument]]
name = "project_id"
description = "The Google Cloud Project ID containing the DCI logs."
type = "string"
required = true
