# Name of the command. This will be used in the slash command: /dci get-diff
name = "get-diff"

# A short description of what the command does.
description = "Fetches the git diff from the latest deployment for a given GCP project and deployment name."

# This is the crucial part for natural language. 
# Gemini will match user prompts against this description.
prompt = "Get the git diff for the latest deployment, specifying the GCP project and deployment name."

# This section defines the tool to be called on the MCP server.
[tool]
# This must match the server name in gemini-extension.json and the tool name in the server code.
call = "dci/devops#get-diff"

# This section defines the parameters for the tool.
# The names 'project' and 'deployment' MUST match the inputSchema in the server code.
[param.project]
prompt = "The GCP project ID"
type = "string"

[param.deployment]
prompt = "The name of the GKE deployment"
type = "string"
